name: deeppurpose-md-env
channels:
  - conda-forge
  - defaults
dependencies:
  - openmm
  - openff-toolkit
  - pdbfixer
  - rdkit
  - pip
  - pip:
      - meeko
      - vina
      - scipy
      - gemmi
      - biopython
      - pubchempy
      - transformers
      - torch
      - tqdm
      - matplotlib
      - pandas
      - pandas-flavor
      - subword-nmt
